version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PW}
            - MYSQL_DATABASE=${DB_NAME}
        volumes: 
            - "./mysql/data/:/docker-entrypoint-initdb.d/"
        restart: always
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./php-fpm/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./:/var/www/html
        depends_on:
            - mysql
        restart: always
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - ./:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        restart: always
